openapi: 3.1.0
info:
  title: User Auth API
  version: 1.0.0
  description: Email and password authentication for 002-user-auth

servers:
  - url: /api/v1
    description: Base path

paths:
  /auth/sign-up:
    post:
      summary: Create account (sign up)
      operationId: signUp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '201':
          description: Account created and signed in
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
                example: SESSION=...; HttpOnly; Path=/; SameSite=Strict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error (invalid email, weak password, email already exists)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/sign-in:
    post:
      summary: Sign in with email and password
      operationId: signIn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Signed in successfully
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Validation error (empty fields, invalid format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/sign-out:
    post:
      summary: Sign out (invalidate session)
      operationId: signOut
      security:
        - sessionAuth: []
      responses:
        '204':
          description: Signed out successfully
        '401':
          description: Not authenticated

  /auth/me:
    get:
      summary: Get current user (authenticated)
      operationId: getCurrentUser
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Current user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated

components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: SESSION

  schemas:
    SignUpRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        password:
          type: string
          minLength: 8
          description: At least one letter, one digit

    SignInRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
